// Generated by gencpp from file franka_example_controllers/JointStates.msg
// DO NOT EDIT!


#ifndef FRANKA_EXAMPLE_CONTROLLERS_MESSAGE_JOINTSTATES_H
#define FRANKA_EXAMPLE_CONTROLLERS_MESSAGE_JOINTSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_example_controllers
{
template <class ContainerAllocator>
struct JointStates_
{
  typedef JointStates_<ContainerAllocator> Type;

  JointStates_()
    : time(0.0)
    , q_r()
    , q_v()
    , q()
    , dotq()
    , tau_commanded()
    , tau_desired()
    , tau_measured()  {
      q_r.assign(0.0);

      q_v.assign(0.0);

      q.assign(0.0);

      dotq.assign(0.0);

      tau_commanded.assign(0.0);

      tau_desired.assign(0.0);

      tau_measured.assign(0.0);
  }
  JointStates_(const ContainerAllocator& _alloc)
    : time(0.0)
    , q_r()
    , q_v()
    , q()
    , dotq()
    , tau_commanded()
    , tau_desired()
    , tau_measured()  {
  (void)_alloc;
      q_r.assign(0.0);

      q_v.assign(0.0);

      q.assign(0.0);

      dotq.assign(0.0);

      tau_commanded.assign(0.0);

      tau_desired.assign(0.0);

      tau_measured.assign(0.0);
  }



   typedef double _time_type;
  _time_type time;

   typedef boost::array<double, 7>  _q_r_type;
  _q_r_type q_r;

   typedef boost::array<double, 7>  _q_v_type;
  _q_v_type q_v;

   typedef boost::array<double, 7>  _q_type;
  _q_type q;

   typedef boost::array<double, 7>  _dotq_type;
  _dotq_type dotq;

   typedef boost::array<double, 7>  _tau_commanded_type;
  _tau_commanded_type tau_commanded;

   typedef boost::array<double, 7>  _tau_desired_type;
  _tau_desired_type tau_desired;

   typedef boost::array<double, 7>  _tau_measured_type;
  _tau_measured_type tau_measured;





  typedef boost::shared_ptr< ::franka_example_controllers::JointStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_example_controllers::JointStates_<ContainerAllocator> const> ConstPtr;

}; // struct JointStates_

typedef ::franka_example_controllers::JointStates_<std::allocator<void> > JointStates;

typedef boost::shared_ptr< ::franka_example_controllers::JointStates > JointStatesPtr;
typedef boost::shared_ptr< ::franka_example_controllers::JointStates const> JointStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_example_controllers::JointStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_example_controllers::JointStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_example_controllers::JointStates_<ContainerAllocator1> & lhs, const ::franka_example_controllers::JointStates_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.q_r == rhs.q_r &&
    lhs.q_v == rhs.q_v &&
    lhs.q == rhs.q &&
    lhs.dotq == rhs.dotq &&
    lhs.tau_commanded == rhs.tau_commanded &&
    lhs.tau_desired == rhs.tau_desired &&
    lhs.tau_measured == rhs.tau_measured;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_example_controllers::JointStates_<ContainerAllocator1> & lhs, const ::franka_example_controllers::JointStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_example_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::franka_example_controllers::JointStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_example_controllers::JointStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_example_controllers::JointStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_example_controllers::JointStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_example_controllers::JointStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_example_controllers::JointStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_example_controllers::JointStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b30f8845b7f2795ceda78d928f162e6a";
  }

  static const char* value(const ::franka_example_controllers::JointStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb30f8845b7f2795cULL;
  static const uint64_t static_value2 = 0xeda78d928f162e6aULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_example_controllers::JointStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_example_controllers/JointStates";
  }

  static const char* value(const ::franka_example_controllers::JointStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_example_controllers::JointStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n"
"float64[7] q_r\n"
"float64[7] q_v\n"
"float64[7] q\n"
"float64[7] dotq\n"
"float64[7] tau_commanded\n"
"float64[7] tau_desired\n"
"float64[7] tau_measured\n"
;
  }

  static const char* value(const ::franka_example_controllers::JointStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_example_controllers::JointStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.q_r);
      stream.next(m.q_v);
      stream.next(m.q);
      stream.next(m.dotq);
      stream.next(m.tau_commanded);
      stream.next(m.tau_desired);
      stream.next(m.tau_measured);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_example_controllers::JointStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_example_controllers::JointStates_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "q_r[]" << std::endl;
    for (size_t i = 0; i < v.q_r.size(); ++i)
    {
      s << indent << "  q_r[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_r[i]);
    }
    s << indent << "q_v[]" << std::endl;
    for (size_t i = 0; i < v.q_v.size(); ++i)
    {
      s << indent << "  q_v[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q_v[i]);
    }
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "dotq[]" << std::endl;
    for (size_t i = 0; i < v.dotq.size(); ++i)
    {
      s << indent << "  dotq[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.dotq[i]);
    }
    s << indent << "tau_commanded[]" << std::endl;
    for (size_t i = 0; i < v.tau_commanded.size(); ++i)
    {
      s << indent << "  tau_commanded[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau_commanded[i]);
    }
    s << indent << "tau_desired[]" << std::endl;
    for (size_t i = 0; i < v.tau_desired.size(); ++i)
    {
      s << indent << "  tau_desired[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau_desired[i]);
    }
    s << indent << "tau_measured[]" << std::endl;
    for (size_t i = 0; i < v.tau_measured.size(); ++i)
    {
      s << indent << "  tau_measured[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.tau_measured[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_EXAMPLE_CONTROLLERS_MESSAGE_JOINTSTATES_H
